services:
  # Banco de Dados
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  # API Node.js
  api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      ORIGIN: ${ORIGIN}
    command: >
      sh -c "
        echo 'â³ Aguardando o bancoâ€¦' &&
        until pg_isready -h db -p 5432 -U ${POSTGRES_USER}; do sleep 1; done &&

        echo 'ğŸ”§ Gerando Prisma Clientâ€¦' &&
        npx prisma generate &&

        echo 'ğŸš€ Aplicando migrationsâ€¦' &&
        npx prisma migrate deploy &&

        echo 'ğŸŒ± Rodando seed' &&
        npx prisma db seed &&

        echo 'ğŸ‰ Iniciando a aplicaÃ§Ã£oâ€¦' &&
        npm start
      "
volumes:
  db_data:
